baseurl = "https://2qov3b.github.io/"
title = "Ken Shen's Idea Pool"
copyright = "Copyright &copy; 2020 - Ken Shen"
canonifyurls = true
theme = "kiera"
publishDir = "public"
hasCJKLanguage = true

## kiera theme settings
paginate = 7
summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

## Hugo Built-in Features
disqusShortname = ""
googleAnalytics = ""
enableRobotsTXT = true

builddrafts = false
languageCode = "ja-jp"


# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "Ken"
    github = ""
    #gitlab = "username"
    #linkedin = "username"
    #facebook = "username"
    twitter = ""
    instagram = ""
    #stackoverflow = "username"
    youtube = "user/username" # or channel/channelname

[params]
    tagline = "Prepare for an uncertain future."
    #description = "description"
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    #favicon = ""
    #utterancesRepo = "https://github.com/MyRepo"
    #utterancesIssueTerm = "pathname"
    #homepageLength = 10


[[menu.main]]
    identifier = "works"
    name = "Works"
    url = "content/works"
    weight = 5
