baseurl = "https://2qov3b.github.io/"
title = "Ken Ken Blog"
copyright = "Copyright &copy; 2020 - Ken Ken"
canonifyurls = true
theme = "kiera"
publishDir = "public"
hasCJKLanguage = true

## kiera theme settings
paginate = 3
summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

## Hugo Built-in Features
disqusShortname = ""
googleAnalytics = ""
enableRobotsTXT = true

builddrafts = false
languageCode = "ja-jp"


# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "Ken"
    github = ""
    #gitlab = "username"
    #linkedin = "username"
    #facebook = "username"
    twitter = ""
    instagram = ""
    #stackoverflow = "username"
    youtube = "user/username" # or channel/channelname

[params]
    tagline = "コロナは怖い！！！- tagline"
    description = "悪霊退散 - description"
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    #favicon = ""
    #utterancesRepo = "https://github.com/MyRepo"
    #utterancesIssueTerm = "pathname"
    #homepageLength = 10

[[menu.main]]
    identifier = "workers"
    name = "Workers"
    url = "/workers"
    weight = 5


[[menu.main]]
    identifier = "pokers"
    name = "Pokers"
    url = "/pokers"
    weight = 5

[[menu.main]]
    identifier = "hackers"
    name = "Hackers"
    url = "/hackers"
    weight = 5

[[menu.main]]
    identifier = "examples"
    name = "Exs"
    url = "/examples"
    weight = 5

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10
